services:
  - type: web
    name: course-finder-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: RENDER
        value: "true"
      - key: BOT_TOKEN
        sync: false
      - key: SERPAPI_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
